version: 2
jobs:
  deploy:
    docker:
      - image: node
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - run: mv build/* docs
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'master' ]; then
              git config user.email "stackdumper@gmail.com"
              git config user.name "stackdumper"

              git add docs -f docs
              git commit --allow-empty -m "$(git log master -1 --pretty=%B)"

              git push git@github.com:stackdumper/stackdumper.com.git master
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy
