version: 2
jobs:
  deploy:
    docker:
      - image: node
    steps:
      - checkout
      - run: npm ci
      - run: npm run build
      - deploy:
          name: Deploy Release to GitHub
          command: |
            mv build /tmp/build

            git config user.email "stackdumper@gmail.com"
            git config user.name "stackdumper"

            git branch -D master
            git checkout --orphan master
            git rm --cached -rf .
            mv /tmp/build docs

            git add docs
            git commit --allow-empty -m "Build"

            git push git@github.com:stackdumper/stackdumper.com.git master -f
workflows:
  version: 2
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - source
